"""add migration for user

Revision ID: a45589d92e70
Revises: 
Create Date: 2023-06-02 15:38:52.994334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45589d92e70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=40), nullable=True),
    sa.Column('email_address', sa.String(length=50), nullable=True),
    sa.Column('insurance_plan_name', sa.String(length=200), nullable=True),
    sa.Column('insured_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
