"""empty message

Revision ID: b3cf2a913712
Revises: 3f4f35d9ef54
Create Date: 2023-06-02 19:08:12.802814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3cf2a913712'
down_revision = '3f4f35d9ef54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('insurance')
    op.drop_table('insuranceplan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insuranceplan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('insurance_plan_name', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('insured_amount', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('insurance_plan_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['insurance_plan_id'], ['insuranceplan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('email_address', sa.VARCHAR(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
