"""update user schema

Revision ID: dcb0a560e12c
Revises: b3cf2a913712
Create Date: 2023-06-02 19:14:23.318054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb0a560e12c'
down_revision = 'b3cf2a913712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insuranceplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insurance_plan_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('insurance_plan_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=40), nullable=False),
    sa.Column('email_address', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email_address'), ['email_address'], unique=True)

    op.create_table('insurance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insured_amount', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('insurance_plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['insurance_plan_id'], ['insuranceplan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insurance')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email_address'))

    op.drop_table('user')
    op.drop_table('insuranceplan')
    # ### end Alembic commands ###
